Repository gbowne1/gradebook-management-system, pull requests merged in 2024-02, with the labels that each got.

#10 Query feature and code normalization
  .gitignore
  CMakeLists.txt
  dataframe.cpp
  dataframe.h
  exceptions.cpp
  exceptions.h
  gradebook.cpp
  gradebook.h
  permissions.cpp
  permissions.h
  utils.h
Labels: enhancement

#11 improving permissions and permission scopes
  permissions.cpp
  permissions.h
Labels: enhancement

#13 Setup unit tests + Organize directories
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  CMakeLists.txt
  gradebook/CMakeLists.txt
  gradebook/assets/assignmentdata.csv
  gradebook/assets/classdata.csv
  gradebook/assets/grades.csv
  gradebook/assets/studentdata.csv
  gradebook/assets/teacherdata.csv
  gradebook/include/dataframe.h
  gradebook/include/exceptions.h
  gradebook/include/gradebook.h
  gradebook/include/permissions.h
  gradebook/include/utils.h
  gradebook/source/dataframe.cpp
  gradebook/source/exceptions.cpp
  gradebook/source/gradebook.cpp
  gradebook/source/main.cpp
  gradebook/source/permissions.cpp
  gradebook/source/utils.cpp
  tests/CMakeLists.txt
  tests/assets/assignmentdata.csv
  tests/assets/classdata.csv
  tests/assets/grades.csv
  tests/assets/studentdata.csv
  tests/assets/teacherdata.csv
  tests/tests/StudentTest.cpp
Labels: enhancement

#14 Improve README.md
  README.md
Labels: documentation

#15 Improving the Gradebook program initial code
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  CMakeLists.txt
  README.md
  gradebook/CMakeLists.txt
  gradebook/include/dataframe.h
  gradebook/include/exceptions.h
  gradebook/include/utils.h
  gradebook/source/dataframe.cpp
  gradebook/source/exceptions.cpp
  gradebook/source/main.cpp
  gradebook/source/permissions.cpp
  gradebook/source/utils.cpp
Labels: enhancement

#17 C++ 14 & Student, Teacher, Assignment, Grade Unit tests
  .vscode/c_cpp_properties.json
  .vscode/settings.json
  gradebook/include/exceptions.h
  gradebook/source/exceptions.cpp
  gradebook/source/gradebook.cpp
  gradebook/source/main.cpp
  tests/CMakeLists.txt
  tests/assets/assignmentdata.csv
  tests/assets/grades.csv
  tests/include/fixtures/assignment_test_fixture.h
  tests/include/fixtures/grade_test_fixture.h
  tests/include/fixtures/student_test_fixture.h
  tests/include/fixtures/teacher_test_fixture.h
  tests/src/fixtures/assignment_test_fixture.cpp
  tests/src/fixtures/grade_test_fixture.cpp
  tests/src/fixtures/student_test_fixture.cpp
  tests/src/fixtures/teacher_test_fixture.cpp
  tests/src/tests/assignment_test.cpp
  tests/src/tests/grade_test.cpp
  tests/src/tests/student_test.cpp
  tests/src/tests/teacher_test.cpp
  tests/tests/StudentTest.cpp
Labels: enhancement, testing

#19 [Feature] adding a basic report card generator
  gradebook/include/reportgenerator.h
  gradebook/source/reportgenerator.cpp
Labels: enhancement

#20 [TODO] add attendance csv file
  gradebook/assets/attendance.csv
Labels: data

#21 adding intitial glog implementation file
  gradebook/source/logs.cpp
Labels: enhancement
